theme: jekyll-theme-slate
title: Is the mortgage lending market fair to non-white applicants?
description: Even when controlling for an individual's debt levels and income, white applicants seem to have easier access to the housing market.
